# Azure CloudNation WAM MCP Server Configuration

# Server settings
server:
  # Port for the MCP server (optional, uses stdin/stdout by default for MCP)
  port: 3000

  # Enable debug logging
  debug: false

  # Cache TTL for module information
  cache_ttl: "1h"

# Module scanning settings
modules:
  # Base path where terraform modules are located
  base_path: "."

  # Patterns to include when scanning for modules
  include_patterns:
    - "terraform-*"

  # Patterns to exclude when scanning
  exclude_patterns:
    - "*.git*"
    - "*/.terraform/*"
    - "*/node_modules/*"

  # Auto-refresh interval
  refresh_interval: "5m"

# Categorization settings
categorization:
  # Minimum word length for text analysis
  min_word_length: 3

  # Minimum co-occurrence count for learning patterns
  min_cooccurrence: 2

  # Enable automatic categorization learning
  auto_learn: true

# Search settings
search:
  # Default result limit
  default_limit: 10

  # Maximum result limit
  max_limit: 100

  # Minimum search score threshold
  min_score_threshold: 1
